### ISSUE TITLE
Add CALC APIs

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/open-gsa-redesign#109]
Add the CALC APIs to the open.gsa.gov/api directory.

Here are the API docs for CALC (Contract Awarded Labor Category)

https://github.com/18F/calc/blob/9873a5b15ca49e3b1d0db52ee407b41c7a9fb080/docs/api.md

**Comment by KehindeOgundolie** [comment]
@rdgsa Hey Ryan, happy to add this. I just need a 2 - 3 sentence description of the API.

**Comment by KehindeOgundolie** [comment]
@rdgsa Can you provide some clarification on this issue when you get the time?

**Comment by rdgsa** [comment]
This looks like an active API, but the web site (https://calc.gsa.gov/) says it is in beta.

I suggest contacting the owner ( calc@gsa.gov) and asking them to provide description for the API in the format:

`- title: Contract-Awarded Labor Category (CALC) API
  description:  (also include whether this is live or not)
  url: (not sure of this, because the GitHub repo has a lot of branches...)
`

**Comment by Ryandaydev** [comment]
This is done.
