### ISSUE TITLE
data.json is hosted here

### ISSUE THREAD

**Issue by rdgsa** [GSA/open-gsa-redesign#22]
Have we considered having the data.json file on the redesigned page? This is managed by Cindy on the production site to meet open data objections:

open.gsa.gov/data.json

**Comment by saracope** [comment]
Also a comment from @afeld for this one: 

I was trying to publish the IT Standards Profile list (GSA/data#37), and was surprised at how many places I had to jump around and people I needed to ask in order to figure out how to get something published "the right way"...and I'm technical and almost competent! Would be great to have a place to point people who have the question "I have some data that I want to make available...what do I do?" Basically, how do we remove the friction from publishing data (responsibly) at GSA?

**Comment by saracope** [comment]
Data.json has been moved.
