### ISSUE TITLE
Code.json update to add USWDS

### ISSUE THREAD

**Issue by saracope** [GSA/open-gsa-redesign#270]
A week or so ago I submitted to the GSA code inventory form to have several USWDS repos added to the inventory for GSA. A couple of questions:

1. ) Is it possible to just add the [USWDS org](https://github.com/uswds) to the family of GSA repos instead of adding each repo individually? That might make it easier to add and maintain.
2. ) It looks like the code.json hasn't been updated recently. Any idea how long it usually takes to get items added?

Thanks!

(tagging @thisisdano for visibility)

**Comment by jfredrickson5** [comment]
Hey @saracope!

> 1) Is it possible to just add the USWDS org to the family of GSA repos instead of adding each repo individually? That might make it easier to add and maintain.

Sure thing. We can include USWDS in the GSA code.json when we do the next harvest. If you have private repos in the USWDS org that need to be inventoried, then either someone on the USWDS end needs to run the harvest script, or USWDS can give me access to the org so that the script pulls in the private repo metadata.

> 2) It looks like the code.json hasn't been updated recently. Any idea how long it usually takes to get items added?

We actually never had a scheduled automatic update for code.json but can do it pretty quickly. We want a CI system or similar to generate code.json, but it's on the backlog.

**Comment by saracope** [comment]
Ok, sounds good. There aren't any private repos in USWDS currently. Is it possible to get that update this week?

Thanks!

**Comment by jfredrickson5** [comment]
Yup, will do.

**Comment by jfredrickson5** [comment]
@saracope This took longer than expected since we kept hitting the GitHub API rate limits with the inventory script due to the number of repos we scan! I'll have this online today, though.

**Comment by saracope** [comment]
Thanks!
