### ISSUE TITLE
Code.json repositoryURL change

### ISSUE THREAD

**Issue by saracope** [GSA/open-gsa-redesign#290]
It looks like in the code.json file, each `repositoryURL` has changed from the last version. 

For example, previously for code-gov-front-end, the `repositoryURL` was linking to:
https://github.com/GSA/code-gov-front-end

but now it's linking directly to the git download
git://github.com/GSA/code-gov-front-end.git

which breaks the project view on code.gov.

I think this would be more appropriate for the downloadURL field instead. Maybe @RicardoAReyes can verify that. Here's is the [schema](https://code.gov/about/compliance/inventory-code).

Can the `repositoryURL` be reverted back?

**Comment by jfredrickson5** [comment]
We switched over to the [LLNL scraper script](https://github.com/LLNL/scraper) due to its ability to handle GitHub API rate limits. It uses the git:// URL for repositoryURL and it doesn't seem to be configurable. I'll do a search and replace all on the code.json for now.

The git:// URL is correct, though, according to the schema. If the intention is to have web-only URLs (http, https), then the schema should be updated. Right now the code.json file passes the [validation check](https://code.gov/about/compliance/inventory-code/validate-schema).

**Comment by saracope** [comment]
Thanks, Jeff. I'll bring this up with the team.
