### ISSUE TITLE
API directory navigation

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/open-gsa-redesign#513]
New API directory looks great! Maybe add search, filters, or ToC. As the page grows and requires pagination, this will be an even faster way for users to find specific APIs.

**Comment by mvogelgesang** [comment]
@jcastle-zz this could be really beneficial. A ToC and anchor links could allow someone to go from a search engine result directly to the API listed in the directory. Today, the user is sent to the top of the page rather than the relevant section. For example, search "Touchpoints API GSA" in Google/Bing and you can see the behavior. I'd be happy to submit this as a contribution if folks are interested
